name: karam
description: NYUAD 2020 Hackathon project.
version: 1.0.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  conditional_builder: ^1.0.2
  #firebase specific UI
  firestore_ui: 
    git: git@github.com:bigworld12/firestore_ui.git
  
  curved_navigation_bar: ^0.3.2
  #firebase
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  firebase_storage: ^3.1.5
  #close proximity check
  geoflutterfire: ^2.1.0
  google_maps_flutter: ^0.5.26
  cache_image: ^1.0.5
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.1
  flutter_launcher_icons: "^0.7.3"
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Cantarell
      fonts:
        - asset: assets/fonts/cantarell/Cantarell-Regular.ttf
        - asset: assets/fonts/cantarell/Cantarell-Oblique.ttf
          style: italic
        - asset: assets/fonts/cantarell/Cantarell-BoldOblique.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/cantarell/Cantarell-Bold.ttf          
          weight: 700
